### ISSUE TITLE
Leo´s devices are no longer shown?

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#105]
Described in team meeting ... Ask Leo for details? 
- Contact industry Parnter regarding ble devices

@Chippelius: Please provide a description and a solution.

**Comment by Chippelius** [comment]
The App now only shows Bluetooth Low Energy Devices, not regular Bluetooth devices. This means, e.g. Apple Airpods do show up, while my off-brand in-ear Bluetooth headphones do not, even though they are visible (even with a readable name) in my Bluetooth settings.
 * Is this expected behavior as intended by the industry partner?
 * What about the test devices they were talking about? When can we expect those / will those even arrive at all, since they are already overdue so much?

**Comment by codingwithelijah** [comment]
> The App now only shows Bluetooth Low Energy Devices, not regular Bluetooth devices. This means, e.g. Apple Airpods do show up, while my off-brand in-ear Bluetooth headphones do not, even though they are visible (even with a readable name) in my Bluetooth settings.
> 
> * Is this expected behavior as intended by the industry partner?
> * What about the test devices they were talking about? When can we expect those / will those even arrive at all, since they are already overdue so much?

Great point, @Chippelius! I just added it to the respective issue (#103).

**Comment by Chippelius** [comment]
Independently of the test-devices we will receive now, we should discuss once more whether we want to show available devices without human-readable name (e.g., as "Unknown Device") or not.
