### ISSUE TITLE
Research options for geolocation solution 

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#22]
## User story
1. As a SD
2. I want / need to get an understanding on how to integrate geolocating
3. So that I am ready to implement the actual feature

## Acceptance criteria
- [x] * got understanding of how geolocating works
- [x] * got understanding of how the implementation works
- [x] * NOTE: No implementation here. 
- [x] * Communicate next steps to POs

**Comment by jannikbmc** [comment]
**Geolocation solution:** [**Xamarin.Essentials** Geolocation](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?WT.mc_id=xamarin-c9-jamont&tabs=android) or **Xamarin Forms plugin**

The go to is the essentials and not the add on, since it has a massive speed up
in getting the geolocation, which we basically want to have a smooth
application.

It is basically a library, so import it `using
Xamarin.Essentials;`, define functions using their methods, map them to a
button or else.

I followed a [simpleinstruction](https://www.c-sharpcorner.com/article/xamarin-forms-geolocation-using-xamarin-essentials/) in an empty project    and i got
my geolocation printed on screen, whenever i clicked a button.
Nice thing, one can choose different accuracies in measuring the GPS location.
And it directly opens a window to ask for permission to use GPS.

Works for both Android and iOS. I only tested it for Android on my phone.

**Using a map**

That's all? No, we further want to see the geolocation as a Pin on the map.

So again, import `using Xamarin.Essentials.Map;`, create a new button and
add a function to open maps at the latest geolocation.

This could be used to start the navigation to the latest location of your
lost device. Downgrade, it's just an `OpenAsync` call and not shown in the app itself.

I extended the app example view with another button, that simply called the
function to open the local maps application with the current selected position
and it worked! Easy.

But we also want to view a map inside of our application!

**Showing a map in app**

So, we could use the [**Xamarin.GoogleMaps**](https://github.com/amay077/Xamarin.Forms.GoogleMaps) provided by `amay077`, or   the [**Xamarin.Forms.Map**](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/)

The go to here would be `Xamarin.Forms.Map`, since we are creating a Xamarin
Forms App and not just an Android app. The differences are not that much and i think using Google Maps would require iOS users to also have this application downloaded, whereas the Xamarin.Forms solution simply display the local maps app of the device.

For Android, before using the API, we have to [generate a Google Maps API key (requires a Google Dev  Account)](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key?tabs=windows).

For iOS, we need some key to use the location, but this would be needed anyway.

Fun fact: One can create icons itself for display on the map :D

There are a lot of [tutorials](https://riptutorial.com/xamarin-forms/example/13637/adding-a-map-in-xamarin-forms--xamarin-studio-) and [how-to's](https://www.xamarinhelp.com/xamarin-forms-maps/) and the [documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/setup) itself is explaining everything as well.
