### ISSUE TITLE
Write test for database

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#64]
@NicoStellwag: Could you update the description of the issue here?

**Comment by NicoStellwag** [comment]
## User story
1. As a team member
3. I want to have 70 percent code coverage for the added database service
4. So that I can fullfill the requirement of our stakeholder / industry partner 

## Acceptance Criteria
- [x] Code coverage of database service above 70 percent

## Further description
- also see #26
